apiVersion: apps/v1
kind: Deployment
metadata:
  name: vl-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vl-learning
  template:
    metadata:
      labels:
        app: vl-learning
    spec:
      containers:
      - name: vl-learning
        image: informaticoloco/vl-learning_backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80