# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.9'
services:
  app:
    #image: informaticoloco/vl-learning_backend:latest  # Imagen que subiste a Docker Hub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=LOCAL  # Si tienes variables de entorno
      - MONGO_URI=mongodb://root:password@mongodb:27017  # Cadena de conexión en local
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVEN_LABS_API_KEY=${ELEVEN_LABS_API_KEY}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db  # Ruta en local para almacenar los datos de MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password